@startuml
!include <C4/C4_Context>
left to right direction

title Контекстная диаграмма C1: Экосистема "Теплый дом"

Person(user, "Пользователь", "Владелец умного дома")

System(warm_house, "Система 'Теплый дом'", "SaaS через web-портал и МП для управления умным домом \n Включает в себя управление: \n -Отоплением \n -Светом \n -Камерами \n -Воротамми")
System_Ext(devices, "Умные устройства", "Датчики отопления, умные лампы/выключатели, датчики движения, камеры, датчики открытия ворот")
System_Ext(payment, "Платежный сервис", "СБП/SberPay")

' Взаимодействия
user --> warm_house : "Управление через веб\n• Настройка и программирование сценариев\n• Просмотр телеметрии"
warm_house --> devices : "Сбор данных / Управление\nMQTT, HTTP, Zigbee"
devices --> warm_house : "События и телеметрия\nAMQP, CoAP"
warm_house --> payment : "Проверка подписки\nПроведение платежей"


@enduml