@startuml
!include <C4/C4_Context>

Person(user, "Пользователь", "Управляет отоплением и получает данные о температуре")

System(warm_house, "Теплый дом", "Система управления отоплением:\n-  Управление работой отопления \n- Настройка целевых значений")

' Взаимодействия пользователя с системой
Rel(user, warm_house, "Включает отопление", "API")
Rel(user, warm_house, "Выключает отопление", "API")
Rel(user, warm_house, "Устанавливает целевую температуру", "API")
Rel(warm_house, user, "Отображает:\n- Текущую температуру\n- Целевые настройки\n- Статус отопления (ВКЛ/ВЫКЛ)", "Web UI")

@enduml